### ISSUE TITLE
Remove tag workflow-bootstrap from template

### ISSUE THREAD

**Issue by masayag** [dmartinol/workflow-gpt#1]
The [tag](https://github.com/dmartinol/workflow-gpt/blob/main/template/template.yaml#L8) is the same as the workflow type. When both are shown one next to another as in the screenshot, seems we can spare the tag and save a tiny bit of UX space :-) 

![Selection_082](https://github.com/dmartinol/workflow-gpt/assets/316242/9813bd12-568c-4666-b44d-c5f38be68258)

**Comment by dmartinol** [comment]
closed by commit 7aa82aba8941140bb25e0c76fa9c913619d25841
